### ISSUE TITLE
jensen shannon divergence calculation

### ISSUE THREAD

**Issue by apmoore1** [sebastianruder/learn-to-select-data#1]
Within the jensen_shannon_divergence function in the [similarity file](https://github.com/sebastianruder/learn-to-select-data/blob/master/similarity.py) should the following line be this:

sim = 1 - 0.5 * (scipy.stats.entropy(repr1, avg_repr) + scipy.stats.entropy(repr1, avg_repr))

and not this:

sim = 1 - 0.5 * (scipy.stats.entropy(repr1, avg_repr) + scipy.stats.entropy(repr2, avg_repr))

**Comment by sebastianruder** [comment]
Thanks for pointing this out! You're totally right. That error must have slipped through when I refactored the code.
