### ISSUE TITLE
bilstm_tagger.src.lib missing

### ISSUE THREAD

**Issue by mzhang001** [sebastianruder/learn-to-select-data#3]
```learn-to-select-data/bilstm_tagger/src/simplebilty.py```

```
from bilstm_tagger.src.lib.mnnl import FFSequencePredictor, Layer, RNNSequencePredictor, BiRNNSequencePredictor
from bilstm_tagger.src.lib.mio import read_conll_file, load_embeddings_file
```
bilstm_tagger.src.lib is missing
In the original repo, this library exists.

**Comment by sebastianruder** [comment]
Thanks for pointing this out. Apparently the automatically generated `.gitignore` ignored files in `lib` directories and I missed this before.
I've added them now in [this commit](https://github.com/sebastianruder/learn-to-select-data/commit/4d3659cdfa097dea9cfd13c3260ae373a0461181).
