### ISSUE TITLE
Usage for different evaluation task

### ISSUE THREAD

**Issue by matanox** [sebastianruder/learn-to-select-data#4]
Hi,

The article is quite fascinating and very impressing in its methodological rigor and the breadth of validation tasks. And now, coming to adapt the method for a task that is not one of the ones used for validation in the paper ― e.g. a classification task (and not sentiment analysis, part-of-speech tagging, or parsing), I wonder whether anyone may kindly point out the point in the code to intervene for this sake, or more generally, how to use this project for _a scenario where the task is not one of the three employed here_.

I ask this not to avoid studying the code per-se, but rather as I'm not currently sure from the project structure, whether there's a certain pipeline of executions (of the different python executables) that needs to be taken in order to materialize a result. The documentation is very good, but somewhat oriented to reproducing the specific experiments, whereas I wish to try out the code, as mentioned above, for a different downstream task...  

I am eager to hopefully have your comments, regarding this great work vis-a-vis my use case for it.

Thanks in advance!

**Comment by sebastianruder** [comment]
Hi,

Thanks for your interest! The best thing to do would be to start having by having a look at [this section](https://github.com/sebastianruder/learn-to-select-data#adding-a-new-task). Let me know if you have any questions.

**Comment by matanox** [comment]
Oh, thanks for opening my eyes to it!
