### ISSUE TITLE
Data Split for SANCL 2012

### ISSUE THREAD

**Issue by slouvan** [sebastianruder/learn-to-select-data#6]
Hi @sebastianruder ,
I'm currently trying to reproduce your experiment using the SANCL 2012 data. I have obtained the SANCL 2012 LDC but I am not clear how did you split the data into train, dev, and test. 
In the LDC data they don't provide the split and also the CONLL format of the annotation.

Can you explain in more details about this? It would be helpful if you have the scripts that process the SANCL 2012 data that construct the split and conll data format that are used by your code.

**Comment by sebastianruder** [comment]
Hi @bplank, could you help out here and provide information how you obtained the splits?

**Comment by bplank** [comment]
Hi @slouvan 
thanks for your interest in our work. The split comes from the SANCL shared task [1]. I checked out the README of SANCL, but there is no info on how the splits were obtained.. 
Please send me a PM.


[1] Syntactic Analysis of Non-Canonical Language (SANCL) - Shared Task
https://sites.google.com/site/sancl2012/home/shared-task
